#!/bin/zsh

TASK_REPORT=ready

alias t='clear; task'

_t() {
	clear; task $* && task $TASK_REPORT
}

_tc() {
	task $* && clear && task $TASK_REPORT
}

alias tt='_t'

alias tu='_t undo'
alias ts='_t sync'
alias tr='t ready'
alias tn='t next'

alias ta='_tc add'
alias tan='ta +next'

alias tl='_tc log'
alias tlf='tl +log +food'
alias tlr='tl +log +run'
alias tls='tl +log +suppl'

alias te='_t edit'
alias tst='_t start'
alias tsp='_t stop'

alias td='t diary +log'
alias tdt='td end:today'
alias tdy='td end:yesterday'

tm() {
	args=($*)
	ids=$args[1]
	args[1]=()
	_t $ids modify $args
}

tmn() {
	tm $* +next
}

