;(set-default-font "Ubuntu Mono-10")
;(setq default-directory "~")
;(cd "~")
(put 'upcase-region 'disabled nil)
(windmove-default-keybindings)
;(tool-bar-mode nil)
(column-number-mode t)
(global-hl-line-mode t)
(blink-cursor-mode t)
;(cua-mode t)
(setq ps-paper-type 'a4)
(setq initial-buffer-choice t)
(setq tab-width 2)
(setq visible-bell t)
(setq make-backup-files nil)
(transient-mark-mode t)
(setq search-highlight t)
(setq query-replace-highlight t)
(show-paren-mode t)
(setq show-paren-style 'expression)
(fset 'yes-or-no-p 'y-or-n-p)
(setq default-major-mode 'text-mode)
(set-default 'truncate-lines nil)
;(setq debug-on-error t)
(setq speedbar-use-images nil)
(let ((default-directory "~/.emacs.d/site-lisp/"))
      (normal-top-level-add-to-load-path '("."))
      (normal-top-level-add-subdirs-to-load-path)
)

(set-language-environment 'utf-8)
(set-locale-environment "C")
(setq default-buffer-file-coding-system 'utf-8)
(prefer-coding-system       'utf-8)
(set-default-coding-systems 'utf-8)
(set-terminal-coding-system 'utf-8)
(set-keyboard-coding-system 'utf-8)
(setq global-auto-revert-mode t)
(global-auto-revert-mode t)
;(require 'image)
(global-visual-line-mode t)
(setq inhibit-splash-screen t)
