(setq company-minimum-prefix-length 2)
(setq company-auto-complete nil)
(setq company-show-numbers t)
(setq company-begin-commands '(self-insert-command))
(setq company-minimum-prefix-length nil)

(require 'company)
(global-company-mode t)

(defun indent-or-complete ()
    (interactive)
    (if (looking-at "\\_>")
        (company-complete-common)
      (indent-according-to-mode)))
(global-set-key "\t" 'indent-or-complete)
